services:
  frontend:
    build: ./app
    container_name: frontend
    command: python -u flask_app.py
    ports:
      - "5000:5000"
    env_file:
      - .env_docker
    depends_on:
      - backend

  backend:
    build: ./app
    container_name: backend
    command: python -u fastapi_app.py
    ports:
      - "8000:8000"
    env_file:
      - .env_docker
    depends_on:
      - mongo
      - minio
      - pgvector
      - rabbitmq

  worker:
    build: ./app
    container_name: worker
    command: python -u worker.py
    env_file:
      - .env_docker
    depends_on:
      - mongo
      - minio
      - pgvector
      - rabbitmq
      
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - .data/mongo_data:/data/db 

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - .data/minio_data:/data

  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: py-rag
    ports:
      - "5432:5432"
    volumes:
      - .data/pgvector_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .data/rabbitmq_data:/var/lib/rabbitmq 
