version: '3.8'
services:
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: embeddings
  #   ports:
  #     - "5432:5432"

  python-backend:
    # container-name: python-backend
    build: python-backend
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: .
    network_mode: "stack_default"